services:
  api:
    image: "ghcr.io/metno/victoria-lite:v2.1.5"
    ports:
      - "8000:8000"
    env_file:
      - ${API_ENV:-.victoria_lite_env}
    environment:
      - MONGO_URL=mongo/status
      - MONGO_USER=status
      - MONGO_PASSWORD=password
      - ENABLE_ADMIN_ROUTES=true
      - ENABLE_ZARR=False
      - ENABLE_S3=False
      - ENABLE_DRIFTY=False
      - ENABLE_VOLCANO=False
    volumes:

      - ${VICTORIA_DATA_PATH:-./data}:/data
      - ./config/:/app/data/config_and_info_files/
    depends_on:
      mongo:
        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 10s # Failures in 10 seconds do not mark container as unhealthy
    restart: on-failure

  mongo:
    image: "mongo:8.0"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_USER: status
      MONGO_PASSWORD: password
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    attach: false

  load_config:
    image: "victoria-maps-api"
    command:
      - /bin/bash
      - -lc
      - |
        /scripts/load_config_to_api.py -c /config/ -u http://api:8000/styles
        curl -X 'GET' 'http://api:8000/admin/update-capabilities'
        echo '#### Styles Loaded. Capabilities updated. API is ready to use. ####'
    volumes:
      - ./config/:/config
      - ./scripts:/scripts
    depends_on:
      api:
        condition: service_healthy
