services:
  api:
    image: "ghcr.io/metno/victoria-lite:v1.1.0-beta"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    ports:
      - "8000:8000"
    env_file:
      - ${API_ENV:-.victoria_lite_env}
    environment:
      - MONGO_URL=mongo/status
      - MONGO_USER=status
      - MONGO_PASSWORD=password
      - ENABLE_ADMIN_ROUTES=true
      - ENABLE_ZARR_S3=False
      - ENABLE_DRIFTY=False
      - ENABLE_VOLCANO=False
    volumes:

      - ${VICTORIA_DATA_PATH:-./data}:/data
      - ./config/:/app/data/config_and_info_files/
      - ./entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      mongo:
        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 10s # Failures in 10 seconds do not mark container as unhealthy
    restart: on-failure

  mongo:
    image: "mongo:8.0"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_USER: status
      MONGO_PASSWORD: password
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
